### ISSUE TITLE
TailwindCSS Link in README

### ISSUE THREAD

**Issue by petittitouan** [illacloud/illacloud.com#16]
In the README, the link which appears to link to https://tailwindcss.com links in fact to https://github.com/tailwindcss.com (Which doesn't exists)

What you can put is :
- https://tailwindcss.com (Official Website)
- https://github.com/tailwindcss (Old Official Organization)
- https://github.com/tailwindlabs (Current Official Organization)

**Comment by AruSeito** [comment]
Thanks for your feedback,we fixed it.
